    <?php

    use Illuminate\Database\Seeder;
    use SGH\Models\Cno;

    class CnosTableSeeder extends Seeder
    {
        /**
         * Run the database seeds.
         *
         * @return void
         */
        public function run()
    	{
    		//$this->command->info('---Seeder Cnos ');
    		
    		$cno = new Cno;
    $cno->CNOS_CODIGO = '1111';
    $cno->CNOS_DESCRIPCION = 'MIEMBROS DEL PODER EJECUTIVO (NACIONAL, AUTONÓMICO Y LOCAL) Y DEL PODER LEGISLATIVO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1112';
    $cno->CNOS_DESCRIPCION = 'PERSONAL DIRECTIVO DE LA ADMINISTRACIÓN PÚBLICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1113';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE ORGANIZACIONES DE INTERÉS SOCIAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1120';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES GENERALES Y PRESIDENTES EJECUTIVOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1211';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES FINANCIEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1212';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE RECURSOS HUMANOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1219';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE POLÍTICAS Y PLANIFICACIÓN Y DE OTROS DEPARTAMENTOS ADMINISTRATIVOS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1221';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES COMERCIALES Y DE VENTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1222';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE PUBLICIDAD Y RELACIONES PÚBLICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1223';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE INVESTIGACIÓN Y DESARROLLO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1311';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE PRODUCCIÓN DE EXPLOTACIONES AGROPECUARIAS Y FORESTALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1312';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE PRODUCCIÓN DE EXPLOTACIONES PESQUERAS Y ACUÍCOLAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1313';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE INDUSTRIAS MANUFACTURERAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1314';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE EXPLOTACIONES MINERAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1315';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE EMPRESAS DE ABASTECIMIENTO, TRANSPORTE, DISTRIBUCIÓN Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1316';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE EMPRESAS DE CONSTRUCCIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1321';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE SERVICIOS DE TECNOLOGÍAS DE LA INFORMACIÓN Y LAS COMUNICACIONES (TIC)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1322';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE SERVICIOS SOCIALES PARA NIÑOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1323';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES-GERENTES DE CENTROS SANITARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1324';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE SERVICIOS SOCIALES PARA PERSONAS MAYORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1325';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE OTROS SERVICIOS SOCIALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1326';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE SERVICIOS DE EDUCACIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1327';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE SUCURSALES DE BANCOS, DE SERVICIOS FINANCIEROS Y DE SEGUROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1329';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE OTRAS EMPRESAS DE SERVICIOS PROFESIONALES NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1411';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE HOTELES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1419';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE OTRAS EMPRESAS DE SERVICIOS DE ALOJAMIENTO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1421';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE RESTAURANTES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1422';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE BARES, CAFETERÍAS Y SIMILARES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1429';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE EMPRESAS DE CATERING Y OTRAS EMPRESAS DE RESTAURACIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1431';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE EMPRESAS DE COMERCIO AL POR MAYOR';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1432';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE EMPRESAS DE COMERCIO AL POR MENOR';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1501';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE EMPRESAS DE ACTIVIDADES RECREATIVAS, CULTURALES Y DEPORTIVAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '1509';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES Y GERENTES DE EMPRESAS DE GESTIÓN DE RESIDUOS Y DE OTRAS EMPRESAS DE SERVICIOS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2111';
    $cno->CNOS_DESCRIPCION = 'MÉDICOS DE FAMILIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2112';
    $cno->CNOS_DESCRIPCION = 'OTROS MÉDICOS ESPECIALISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2121';
    $cno->CNOS_DESCRIPCION = 'ENFERMEROS NO ESPECIALIZADOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2122';
    $cno->CNOS_DESCRIPCION = 'ENFERMEROS ESPECIALIZADOS (EXCEPTO MATRONOS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2123';
    $cno->CNOS_DESCRIPCION = 'MATRONOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2130';
    $cno->CNOS_DESCRIPCION = 'VETERINARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2140';
    $cno->CNOS_DESCRIPCION = 'FARMACÉUTICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2151';
    $cno->CNOS_DESCRIPCION = 'ODONTÓLOGOS Y ESTOMATÓLOGOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2152';
    $cno->CNOS_DESCRIPCION = 'FISIOTERAPEUTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2153';
    $cno->CNOS_DESCRIPCION = 'DIETISTAS Y NUTRICIONISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2154';
    $cno->CNOS_DESCRIPCION = 'LOGOPEDAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2155';
    $cno->CNOS_DESCRIPCION = 'ÓPTICOS-OPTOMETRISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2156';
    $cno->CNOS_DESCRIPCION = 'TERAPEUTAS OCUPACIONALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2157';
    $cno->CNOS_DESCRIPCION = 'PODÓLOGOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2158';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE LA SALUD Y LA HIGIENE LABORAL Y AMBIENTAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2159';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE LA SALUD NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2210';
    $cno->CNOS_DESCRIPCION = 'PROFESORES DE UNIVERSIDADES Y OTRA ENSEÑANZA SUPERIOR (EXCEPTO FORMACIÓN PROFESIONAL)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2220';
    $cno->CNOS_DESCRIPCION = 'PROFESORES DE FORMACIÓN PROFESIONAL (MATERIAS ESPECÍFICAS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2230';
    $cno->CNOS_DESCRIPCION = 'PROFESORES DE ENSEÑANZA SECUNDARIA (EXCEPTO MATERIAS ESPECÍFICAS DE FORMACIÓN PROFESIONAL)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2240';
    $cno->CNOS_DESCRIPCION = 'PROFESORES DE ENSEÑANZA PRIMARIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2251';
    $cno->CNOS_DESCRIPCION = 'MAESTROS DE EDUCACIÓN INFANTIL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2252';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN EDUCACIÓN INFANTIL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2311';
    $cno->CNOS_DESCRIPCION = 'PROFESORES DE EDUCACIÓN ESPECIAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2312';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EDUCADORES DE EDUCACIÓN ESPECIAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2321';
    $cno->CNOS_DESCRIPCION = 'ESPECIALISTAS EN MÉTODOS DIDÁCTICOS Y PEDAGÓGICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2322';
    $cno->CNOS_DESCRIPCION = 'PROFESORES DE ENSEÑANZA NO REGLADA DE IDIOMAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2323';
    $cno->CNOS_DESCRIPCION = 'PROFESORES DE ENSEÑANZA NO REGLADA DE MÚSICA Y DANZA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2324';
    $cno->CNOS_DESCRIPCION = 'PROFESORES DE ENSEÑANZA NO REGLADA DE ARTES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2325';
    $cno->CNOS_DESCRIPCION = 'INSTRUCTORES EN TECNOLOGÍAS DE LA INFORMACIÓN EN ENSEÑANZA NO REGLADA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2326';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE LA EDUCACIÓN AMBIENTAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2329';
    $cno->CNOS_DESCRIPCION = 'PROFESORES Y PROFESIONALES DE LA ENSEÑANZA NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2411';
    $cno->CNOS_DESCRIPCION = 'FÍSICOS Y ASTRÓNOMOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2412';
    $cno->CNOS_DESCRIPCION = 'METEORÓLOGOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2413';
    $cno->CNOS_DESCRIPCION = 'QUÍMICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2414';
    $cno->CNOS_DESCRIPCION = 'GEÓLOGOS Y GEOFÍSICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2415';
    $cno->CNOS_DESCRIPCION = 'MATEMÁTICOS Y ACTUARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2416';
    $cno->CNOS_DESCRIPCION = 'ESTADÍSTICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2421';
    $cno->CNOS_DESCRIPCION = 'BIÓLOGOS, BOTÁNICOS, ZOÓLOGOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2422';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS AGRÓNOMOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2423';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS DE MONTES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2424';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS AGRÍCOLAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2425';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS FORESTALES Y DEL MEDIO NATURAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2426';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE LA PROTECCIÓN AMBIENTAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2427';
    $cno->CNOS_DESCRIPCION = 'ENÓLOGOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2431';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS INDUSTRIALES Y DE PRODUCCIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2432';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS EN CONSTRUCCIÓN Y OBRA CIVIL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2433';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS MECÁNICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2434';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS AERONÁUTICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2435';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS QUÍMICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2436';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS DE MINAS, METALÚRGICOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2437';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS AMBIENTALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2439';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2441';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS EN ELECTRICIDAD';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2442';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS ELECTRÓNICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2443';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS EN TELECOMUNICACIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2451';
    $cno->CNOS_DESCRIPCION = 'ARQUITECTOS (EXCEPTO ARQUITECTOS PAISAJISTAS Y URBANISTAS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2452';
    $cno->CNOS_DESCRIPCION = 'ARQUITECTOS PAISAJISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2453';
    $cno->CNOS_DESCRIPCION = 'URBANISTAS E INGENIEROS DE TRÁFICO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2454';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS GEÓGRAFOS Y CARTÓGRAFOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2461';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS INDUSTRIALES Y DE PRODUCCIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2462';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS DE OBRAS PÚBLICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2463';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS MECÁNICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2464';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS AERONÁUTICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2465';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS QUÍMICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2466';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS DE MINAS, METALÚRGICOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2469';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2471';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS EN ELECTRICIDAD';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2472';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS EN ELECTRÓNICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2473';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS EN TELECOMUNICACIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2481';
    $cno->CNOS_DESCRIPCION = 'ARQUITECTOS TÉCNICOS Y TÉCNICOS URBANISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2482';
    $cno->CNOS_DESCRIPCION = 'DISEÑADORES DE PRODUCTOS Y DE PRENDAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2483';
    $cno->CNOS_DESCRIPCION = 'INGENIEROS TÉCNICOS EN TOPOGRAFÍA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2484';
    $cno->CNOS_DESCRIPCION = 'DISEÑADORES GRÁFICOS Y MULTIMEDIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2511';
    $cno->CNOS_DESCRIPCION = 'ABOGADOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2512';
    $cno->CNOS_DESCRIPCION = 'FISCALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2513';
    $cno->CNOS_DESCRIPCION = 'JUECES Y MAGISTRADOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2591';
    $cno->CNOS_DESCRIPCION = 'NOTARIOS Y REGISTRADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2592';
    $cno->CNOS_DESCRIPCION = 'PROCURADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2599';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DEL DERECHO NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2611';
    $cno->CNOS_DESCRIPCION = 'ESPECIALISTAS EN CONTABILIDAD';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2612';
    $cno->CNOS_DESCRIPCION = 'ASESORES FINANCIEROS Y EN INVERSIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2613';
    $cno->CNOS_DESCRIPCION = 'ANALISTAS FINANCIEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2621';
    $cno->CNOS_DESCRIPCION = 'ANALISTAS DE GESTIÓN Y ORGANIZACIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2622';
    $cno->CNOS_DESCRIPCION = 'ESPECIALISTAS EN ADMINISTRACIÓN DE POLÍTICA DE EMPRESAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2623';
    $cno->CNOS_DESCRIPCION = 'ESPECIALISTAS DE LA ADMINISTRACIÓN PÚBLICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2624';
    $cno->CNOS_DESCRIPCION = 'ESPECIALISTAS EN POLÍTICAS Y SERVICIOS DE PERSONAL Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2625';
    $cno->CNOS_DESCRIPCION = 'ESPECIALISTAS EN FORMACIÓN DE PERSONAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2630';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE EMPRESAS Y ACTIVIDADES TURÍSTICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2640';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE VENTAS TÉCNICAS Y MÉDICAS (EXCEPTO LAS TIC)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2651';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE LA PUBLICIDAD Y LA COMERCIALIZACIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2652';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE RELACIONES PÚBLICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2653';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE LA VENTA DE TECNOLOGÍAS DE LA INFORMACIÓN Y LAS COMUNICACIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2711';
    $cno->CNOS_DESCRIPCION = 'ANALISTAS DE SISTEMAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2712';
    $cno->CNOS_DESCRIPCION = 'ANALISTAS Y DISEÑADORES DE SOFTWARE';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2713';
    $cno->CNOS_DESCRIPCION = 'ANALISTAS, PROGRAMADORES Y DISEÑADORES WEB Y MULTIMEDIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2719';
    $cno->CNOS_DESCRIPCION = 'ANALISTAS Y DISEÑADORES DE SOFTWARE Y MULTIMEDIA NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2721';
    $cno->CNOS_DESCRIPCION = 'DISEÑADORES Y ADMINISTRADORES DE BASES DE DATOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2722';
    $cno->CNOS_DESCRIPCION = 'ADMINISTRADORES DE SISTEMAS Y REDES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2723';
    $cno->CNOS_DESCRIPCION = 'ANALISTAS DE REDES INFORMÁTICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2729';
    $cno->CNOS_DESCRIPCION = 'ESPECIALISTAS EN BASES DE DATOS Y EN REDES INFORMÁTICAS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2810';
    $cno->CNOS_DESCRIPCION = 'ECONOMISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2821';
    $cno->CNOS_DESCRIPCION = 'SOCIÓLOGOS, GEÓGRAFOS, ANTROPÓLOGOS, ARQUEÓLOGOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2822';
    $cno->CNOS_DESCRIPCION = 'FILÓSOFOS, HISTORIADORES Y PROFESIONALES EN CIENCIAS POLÍTICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2823';
    $cno->CNOS_DESCRIPCION = 'PSICÓLOGOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2824';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DEL TRABAJO Y LA EDUCACIÓN SOCIAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2825';
    $cno->CNOS_DESCRIPCION = 'AGENTES DE IGUALDAD DE OPORTUNIDADES ENTRE MUJERES Y HOMBRES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2830';
    $cno->CNOS_DESCRIPCION = 'SACERDOTES DE LAS DISTINTAS RELIGIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2911';
    $cno->CNOS_DESCRIPCION = 'ARCHIVISTAS Y CONSERVADORES DE MUSEOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2912';
    $cno->CNOS_DESCRIPCION = 'BIBLIOTECARIOS, DOCUMENTALISTAS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2921';
    $cno->CNOS_DESCRIPCION = 'ESCRITORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2922';
    $cno->CNOS_DESCRIPCION = 'PERIODISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2923';
    $cno->CNOS_DESCRIPCION = 'FILÓLOGOS, INTÉRPRETES Y TRADUCTORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2931';
    $cno->CNOS_DESCRIPCION = 'ARTISTAS DE ARTES PLÁSTICAS Y VISUALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2932';
    $cno->CNOS_DESCRIPCION = 'COMPOSITORES, MÚSICOS Y CANTANTES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2933';
    $cno->CNOS_DESCRIPCION = 'COREÓGRAFOS Y BAILARINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2934';
    $cno->CNOS_DESCRIPCION = 'DIRECTORES DE CINE, DE TEATRO Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2935';
    $cno->CNOS_DESCRIPCION = 'ACTORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2936';
    $cno->CNOS_DESCRIPCION = 'LOCUTORES DE RADIO, TELEVISIÓN Y OTROS PRESENTADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2937';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE ESPECTÁCULOS TAURINOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '2939';
    $cno->CNOS_DESCRIPCION = 'ARTISTAS CREATIVOS E INTERPRETATIVOS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3110';
    $cno->CNOS_DESCRIPCION = 'DELINEANTES Y DIBUJANTES TÉCNICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3121';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN CIENCIAS FÍSICAS Y QUÍMICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3122';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN CONSTRUCCIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3123';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN ELECTRICIDAD';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3124';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN ELECTRÓNICA (EXCEPTO ELECTROMEDICINA)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3125';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN ELECTRÓNICA, ESPECIALIDAD EN ELECTROMEDICINA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3126';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN MECÁNICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3127';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS Y ANALISTAS DE LABORATORIO EN QUÍMICA INDUSTRIAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3128';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN METALURGIA Y MINAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3129';
    $cno->CNOS_DESCRIPCION = 'OTROS TÉCNICOS DE LAS CIENCIAS FÍSICAS, QUÍMICAS, MEDIOAMBIENTALES Y DE LAS INGENIERÍAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3131';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN INSTALACIONES DE PRODUCCIÓN DE ENERGÍA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3132';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN INSTALACIONES DE TRATAMIENTO DE RESIDUOS, DE AGUAS Y OTROS OPERADORES EN PLANTAS SIMILARES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3133';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN CONTROL DE INSTALACIONES DE PROCESAMIENTO DE PRODUCTOS QUÍMICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3134';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE REFINERÍAS DE PETRÓLEO Y GAS NATURAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3135';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN CONTROL DE PROCESOS DE PRODUCCIÓN DE METALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3139';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN CONTROL DE PROCESOS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3141';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN CIENCIAS BIOLÓGICAS (EXCEPTO EN ÁREAS SANITARIAS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3142';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS AGROPECUARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3143';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS FORESTALES Y DEL MEDIO NATURAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3151';
    $cno->CNOS_DESCRIPCION = 'JEFES Y OFICIALES DE MÁQUINAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3152';
    $cno->CNOS_DESCRIPCION = 'CAPITANES Y OFICIALES DE PUENTE';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3153';
    $cno->CNOS_DESCRIPCION = 'PILOTOS DE AVIACIÓN Y PROFESIONALES AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3154';
    $cno->CNOS_DESCRIPCION = 'CONTROLADORES DE TRÁFICO AÉREO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3155';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN SEGURIDAD AERONÁUTICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3160';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE CONTROL DE CALIDAD DE LAS CIENCIAS FÍSICAS, QUÍMICAS Y DE LAS INGENIERÍAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3201';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES EN INGENIERÍA DE MINAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3202';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE LA CONSTRUCCIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3203';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE INDUSTRIAS ALIMENTICIAS Y DEL TABACO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3204';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE INDUSTRIAS QUÍMICA Y FARMACÉUTICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3205';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE INDUSTRIAS DE TRANSFORMACIÓN DE PLÁSTICOS, CAUCHO Y RESINAS NATURALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3206';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE INDUSTRIAS DE LA MADERA Y PASTERO PAPELERAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3207';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE LA PRODUCCIÓN EN INDUSTRIAS DE ARTES GRÁFICAS Y EN LA FABRICACIÓN DE PRODUCTOS DE PAPEL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3209';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE OTRAS INDUSTRIAS MANUFACTURERAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3311';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN RADIOTERAPIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3312';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN IMAGEN PARA EL DIAGNÓSTICO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3313';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN ANATOMÍA PATOLÓGICA Y CITOLOGÍA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3314';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN LABORATORIO DE DIAGNÓSTICO CLÍNICO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3315';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN ORTOPRÓTESIS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3316';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN PRÓTESIS DENTALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3317';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN AUDIOPRÓTESIS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3321';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS SUPERIORES EN HIGIENE BUCODENTAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3322';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS SUPERIORES EN DOCUMENTACIÓN SANITARIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3323';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS SUPERIORES EN DIETÉTICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3324';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN OPTOMETRÍA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3325';
    $cno->CNOS_DESCRIPCION = 'AYUDANTES FISIOTERAPEUTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3326';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN PREVENCIÓN DE RIESGOS LABORALES Y SALUD AMBIENTAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3327';
    $cno->CNOS_DESCRIPCION = 'AYUDANTES DE VETERINARIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3329';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE LA SANIDAD NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3331';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE LA ACUPUNTURA, LA NATUROPATÍA, LA HOMEOPATÍA, LA MEDICINA TRADICIONAL CHINA Y LA AYURVEDA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3339';
    $cno->CNOS_DESCRIPCION = 'OTROS PROFESIONALES DE LAS TERAPIAS ALTERNATIVAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3401';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE APOYO E INTERMEDIARIOS DE CAMBIO, BOLSA Y FINANZAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3402';
    $cno->CNOS_DESCRIPCION = 'COMERCIALES DE PRÉSTAMOS Y CRÉDITOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3403';
    $cno->CNOS_DESCRIPCION = 'TENEDORES DE LIBROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3404';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE APOYO EN SERVICIOS ESTADÍSTICOS, MATEMÁTICOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3405';
    $cno->CNOS_DESCRIPCION = 'TASADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3510';
    $cno->CNOS_DESCRIPCION = 'AGENTES Y REPRESENTANTES COMERCIALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3521';
    $cno->CNOS_DESCRIPCION = 'MEDIADORES Y AGENTES DE SEGUROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3522';
    $cno->CNOS_DESCRIPCION = 'AGENTES DE COMPRAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3523';
    $cno->CNOS_DESCRIPCION = 'CONSIGNATARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3531';
    $cno->CNOS_DESCRIPCION = 'REPRESENTANTES DE ADUANAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3532';
    $cno->CNOS_DESCRIPCION = 'ORGANIZADORES DE CONFERENCIAS Y EVENTOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3533';
    $cno->CNOS_DESCRIPCION = 'AGENTES O INTERMEDIARIOS EN LA CONTRATACIÓN DE LA MANO DE OBRA (EXCEPTO REPRESENTANTES DE ESPECTÁCULOS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3534';
    $cno->CNOS_DESCRIPCION = 'AGENTES Y ADMINISTRADORES DE LA PROPIEDAD INMOBILIARIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3535';
    $cno->CNOS_DESCRIPCION = 'PORTAVOCES Y AGENTES DE RELACIONES PÚBLICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3539';
    $cno->CNOS_DESCRIPCION = 'REPRESENTANTES ARTÍSTICOS Y DEPORTIVOS Y OTROS AGENTES DE SERVICIOS COMERCIALES NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3611';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE SECRETARÍA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3612';
    $cno->CNOS_DESCRIPCION = 'ASISTENTES JURÍDICO-LEGALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3613';
    $cno->CNOS_DESCRIPCION = 'ASISTENTES DE DIRECCIÓN Y ADMINISTRATIVOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3614';
    $cno->CNOS_DESCRIPCION = 'SECRETARIOS DE CENTROS MÉDICOS O CLÍNICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3621';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE APOYO DE LA ADMINISTRACIÓN PÚBLICA DE TRIBUTOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3622';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE APOYO DE LA ADMINISTRACIÓN PÚBLICA DE SERVICIOS SOCIALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3623';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE APOYO DE LA ADMINISTRACIÓN PÚBLICA DE SERVICIOS DE EXPEDICIÓN DE LICENCIAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3629';
    $cno->CNOS_DESCRIPCION = 'OTROS PROFESIONALES DE APOYO DE LA ADMINISTRACIÓN PÚBLICA PARA TAREAS DE INSPECCIÓN Y CONTROL Y TAREAS SIMILARES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3631';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE LA POLICÍA NACIONAL, AUTONÓMICA Y LOCAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3632';
    $cno->CNOS_DESCRIPCION = 'SUBOFICIALES DE LA GUARDIA CIVIL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3711';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE APOYO DE SERVICIOS JURÍDICOS Y SERVICIOS SIMILARES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3712';
    $cno->CNOS_DESCRIPCION = 'DETECTIVES PRIVADOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3713';
    $cno->CNOS_DESCRIPCION = 'PROFESIONALES DE APOYO AL TRABAJO Y A LA EDUCACIÓN SOCIAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3714';
    $cno->CNOS_DESCRIPCION = 'PROMOTORES DE IGUALDAD DE OPORTUNIDADES ENTRE MUJERES Y HOMBRES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3715';
    $cno->CNOS_DESCRIPCION = 'ANIMADORES COMUNITARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3716';
    $cno->CNOS_DESCRIPCION = 'AUXILIARES LAICOS DE LAS RELIGIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3721';
    $cno->CNOS_DESCRIPCION = 'ATLETAS Y DEPORTISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3722';
    $cno->CNOS_DESCRIPCION = 'ENTRENADORES Y ÁRBITROS DE ACTIVIDADES DEPORTIVAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3723';
    $cno->CNOS_DESCRIPCION = 'INSTRUCTORES DE ACTIVIDADES DEPORTIVAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3724';
    $cno->CNOS_DESCRIPCION = 'MONITORES DE ACTIVIDADES RECREATIVAS Y DE ENTRETENIMIENTO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3731';
    $cno->CNOS_DESCRIPCION = 'FOTÓGRAFOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3732';
    $cno->CNOS_DESCRIPCION = 'DISEÑADORES Y DECORADORES DE INTERIOR';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3733';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN GALERÍAS DE ARTE, MUSEOS Y BIBLIOTECAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3734';
    $cno->CNOS_DESCRIPCION = 'CHEFS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3739';
    $cno->CNOS_DESCRIPCION = 'OTROS TÉCNICOS Y PROFESIONALES DE APOYO DE ACTIVIDADES CULTURALES Y ARTÍSTICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3811';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN OPERACIONES DE SISTEMAS INFORMÁTICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3812';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN ASISTENCIA AL USUARIO DE TECNOLOGÍAS DE LA INFORMACIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3813';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS EN REDES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3814';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE LA WEB';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3820';
    $cno->CNOS_DESCRIPCION = 'PROGRAMADORES INFORMÁTICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3831';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE GRABACIÓN AUDIOVISUAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3832';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE RADIODIFUSIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '3833';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE INGENIERÍA DE LAS TELECOMUNICACIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4111';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE CONTABILIDAD';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4112';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE CONTROL DE PERSONAL Y NÓMINAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4113';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE OFICINA DE SERVICIOS ESTADÍSTICOS, FINANCIEROS Y BANCARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4121';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE CONTROL DE ABASTECIMIENTOS E INVENTARIO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4122';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE OFICINA DE SERVICIOS DE APOYO A LA PRODUCCIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4123';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE LOGÍSTICA Y TRANSPORTE DE PASAJEROS Y MERCANCÍAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4210';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE BIBLIOTECAS Y ARCHIVOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4221';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE SERVICIOS DE CORREOS (EXCEPTO EMPLEADOS DE MOSTRADOR)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4222';
    $cno->CNOS_DESCRIPCION = 'CODIFICADORES Y CORRECTORES DE IMPRENTA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4223';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE SERVICIO DE PERSONAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4301';
    $cno->CNOS_DESCRIPCION = 'GRABADORES DE DATOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4309';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS ADMINISTRATIVOS SIN TAREAS DE ATENCIÓN AL PÚBLICO NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4411';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE INFORMACIÓN AL USUARIO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4412';
    $cno->CNOS_DESCRIPCION = 'RECEPCIONISTAS (EXCEPTO DE HOTELES)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4421';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE AGENCIAS DE VIAJES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4422';
    $cno->CNOS_DESCRIPCION = 'RECEPCIONISTAS DE HOTELES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4423';
    $cno->CNOS_DESCRIPCION = 'TELEFONISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4424';
    $cno->CNOS_DESCRIPCION = 'TELEOPERADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4430';
    $cno->CNOS_DESCRIPCION = 'AGENTES DE ENCUESTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4441';
    $cno->CNOS_DESCRIPCION = 'CAJEROS DE BANCOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4442';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE VENTA DE APUESTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4443';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE SALA DE JUEGOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4444';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE CASAS DE EMPEÑO Y DE PRÉSTAMOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4445';
    $cno->CNOS_DESCRIPCION = 'COBRADORES DE FACTURAS, DEUDAS Y EMPLEADOS AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4446';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE MOSTRADOR DE CORREOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '4500';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS ADMINISTRATIVOS CON TAREAS DE ATENCIÓN AL PÚBLICO NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5000';
    $cno->CNOS_DESCRIPCION = 'CAMAREROS Y COCINEROS PROPIETARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5110';
    $cno->CNOS_DESCRIPCION = 'COCINEROS ASALARIADOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5120';
    $cno->CNOS_DESCRIPCION = 'CAMAREROS ASALARIADOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5210';
    $cno->CNOS_DESCRIPCION = 'JEFES DE SECCIÓN DE TIENDAS Y ALMACENES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5220';
    $cno->CNOS_DESCRIPCION = 'VENDEDORES EN TIENDAS Y ALMACENES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5300';
    $cno->CNOS_DESCRIPCION = 'COMERCIANTES PROPIETARIOS DE TIENDAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5411';
    $cno->CNOS_DESCRIPCION = 'VENDEDORES EN QUIOSCOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5412';
    $cno->CNOS_DESCRIPCION = 'VENDEDORES EN MERCADOS OCASIONALES Y MERCADILLOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5420';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE TELEMARKETING';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5430';
    $cno->CNOS_DESCRIPCION = 'EXPENDEDORES DE GASOLINERAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5491';
    $cno->CNOS_DESCRIPCION = 'VENDEDORES A DOMICILIO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5492';
    $cno->CNOS_DESCRIPCION = 'PROMOTORES DE VENTA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5493';
    $cno->CNOS_DESCRIPCION = 'MODELOS DE MODA, ARTE Y PUBLICIDAD';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5499';
    $cno->CNOS_DESCRIPCION = 'VENDEDORES NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5500';
    $cno->CNOS_DESCRIPCION = 'CAJEROS Y TAQUILLEROS (EXCEPTO BANCOS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5611';
    $cno->CNOS_DESCRIPCION = 'AUXILIARES DE ENFERMERÍA HOSPITALARIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5612';
    $cno->CNOS_DESCRIPCION = 'AUXILIARES DE ENFERMERÍA DE ATENCIÓN PRIMARIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5621';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS AUXILIARES DE FARMACIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5622';
    $cno->CNOS_DESCRIPCION = 'TÉCNICOS DE EMERGENCIAS SANITARIAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5629';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE LOS CUIDADOS A LAS PERSONAS EN SERVICIOS DE SALUD NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5710';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE LOS CUIDADOS PERSONALES A DOMICILIO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5721';
    $cno->CNOS_DESCRIPCION = 'CUIDADORES DE NIÑOS EN GUARDERÍAS Y CENTROS EDUCATIVOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5722';
    $cno->CNOS_DESCRIPCION = 'CUIDADORES DE NIÑOS EN DOMICILIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5811';
    $cno->CNOS_DESCRIPCION = 'PELUQUEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5812';
    $cno->CNOS_DESCRIPCION = 'ESPECIALISTAS EN TRATAMIENTOS DE ESTÉTICA, BIENESTAR Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5821';
    $cno->CNOS_DESCRIPCION = 'AUXILIARES DE VUELO Y CAMAREROS DE AVIÓN, BARCO Y TREN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5822';
    $cno->CNOS_DESCRIPCION = 'REVISORES Y COBRADORES DE TRANSPORTE TERRESTRE';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5823';
    $cno->CNOS_DESCRIPCION = 'ACOMPAÑANTES TURÍSTICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5824';
    $cno->CNOS_DESCRIPCION = 'AZAFATOS DE TIERRA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5825';
    $cno->CNOS_DESCRIPCION = 'GUÍAS DE TURISMO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5831';
    $cno->CNOS_DESCRIPCION = 'SUPERVISORES DE MANTENIMIENTO Y LIMPIEZA EN OFICINAS, HOTELES Y OTROS ESTABLECIMIENTOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5832';
    $cno->CNOS_DESCRIPCION = 'MAYORDOMOS DEL SERVICIO DOMÉSTICO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5833';
    $cno->CNOS_DESCRIPCION = 'CONSERJES DE EDIFICIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5840';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES PROPIETARIOS DE PEQUEÑOS ALOJAMIENTOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5891';
    $cno->CNOS_DESCRIPCION = 'ASISTENTES PERSONALES O PERSONAS DE COMPAÑÍA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5892';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DE POMPAS FÚNEBRES Y EMBALSAMADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5893';
    $cno->CNOS_DESCRIPCION = 'CUIDADORES DE ANIMALES Y ADIESTRADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5894';
    $cno->CNOS_DESCRIPCION = 'INSTRUCTORES DE AUTOESCUELA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5895';
    $cno->CNOS_DESCRIPCION = 'ASTRÓLOGOS, ADIVINADORES Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5899';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE SERVICIOS PERSONALES NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5910';
    $cno->CNOS_DESCRIPCION = 'GUARDIAS CIVILES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5921';
    $cno->CNOS_DESCRIPCION = 'POLICÍAS NACIONALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5922';
    $cno->CNOS_DESCRIPCION = 'POLICÍAS AUTONÓMICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5923';
    $cno->CNOS_DESCRIPCION = 'POLICÍAS LOCALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5931';
    $cno->CNOS_DESCRIPCION = 'BOMBEROS (EXCEPTO FORESTALES)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5932';
    $cno->CNOS_DESCRIPCION = 'BOMBEROS FORESTALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5941';
    $cno->CNOS_DESCRIPCION = 'VIGILANTES DE SEGURIDAD Y SIMILARES HABILITADOS PARA IR ARMADOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5942';
    $cno->CNOS_DESCRIPCION = 'AUXILIARES DE VIGILANTE DE SEGURIDAD Y SIMILARES NO HABILITADOS PARA IR ARMADOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5991';
    $cno->CNOS_DESCRIPCION = 'VIGILANTES DE PRISIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5992';
    $cno->CNOS_DESCRIPCION = 'BAÑISTAS-SOCORRISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5993';
    $cno->CNOS_DESCRIPCION = 'AGENTES FORESTALES Y MEDIOAMBIENTALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '5999';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE LOS SERVICIOS DE PROTECCIÓN Y SEGURIDAD NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6110';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN ACTIVIDADES AGRÍCOLAS (EXCEPTO EN HUERTAS, INVERNADEROS, VIVEROS Y JARDINES)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6120';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN HUERTAS, INVERNADEROS, VIVEROS Y JARDINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6201';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN ACTIVIDADES GANADERAS DE VACUNO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6202';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN ACTIVIDADES GANADERAS DE OVINO Y CAPRINO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6203';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN ACTIVIDADES GANADERAS DE PORCINO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6204';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN APICULTURA Y SERICICULTURA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6205';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN LA AVICULTURA Y LA CUNICULTURA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6209';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN ACTIVIDADES GANADERAS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6300';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN ACTIVIDADES AGROPECUARIAS MIXTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6410';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN ACTIVIDADES FORESTALES Y DEL MEDIO NATURAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6421';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN LA ACUICULTURA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6422';
    $cno->CNOS_DESCRIPCION = 'PESCADORES DE AGUAS COSTERAS Y AGUAS DULCES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6423';
    $cno->CNOS_DESCRIPCION = 'PESCADORES DE ALTURA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '6430';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CUALIFICADOS EN ACTIVIDADES CINEGÉTICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7111';
    $cno->CNOS_DESCRIPCION = 'ENCOFRADORES Y OPERARIOS DE PUESTA EN OBRA DE HORMIGÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7112';
    $cno->CNOS_DESCRIPCION = 'MONTADORES DE PREFABRICADOS ESTRUCTURALES (SÓLO HORMIGÓN)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7121';
    $cno->CNOS_DESCRIPCION = 'ALBAÑILES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7122';
    $cno->CNOS_DESCRIPCION = 'CANTEROS, TRONZADORES, LABRANTES Y GRABADORES DE PIEDRAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7131';
    $cno->CNOS_DESCRIPCION = 'CARPINTEROS (EXCEPTO EBANISTAS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7132';
    $cno->CNOS_DESCRIPCION = 'INSTALADORES DE CERRAMIENTOS METÁLICOS Y CARPINTEROS METÁLICOS (EXCEPTO MONTADORES DE ESTRUCTURAS METÁLICAS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7191';
    $cno->CNOS_DESCRIPCION = 'MANTENEDORES DE EDIFICIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7192';
    $cno->CNOS_DESCRIPCION = 'INSTALADORES DE FACHADAS TÉCNICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7193';
    $cno->CNOS_DESCRIPCION = 'INSTALADORES DE SISTEMAS DE IMPERMEABILIZACIÓN EN EDIFICIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7199';
    $cno->CNOS_DESCRIPCION = 'OTROS TRABAJADORES DE LAS OBRAS ESTRUCTURALES DE CONSTRUCCIÓN NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7211';
    $cno->CNOS_DESCRIPCION = 'ESCAYOLISTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7212';
    $cno->CNOS_DESCRIPCION = 'APLICADORES DE REVESTIMIENTOS DE PASTA Y MORTERO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7221';
    $cno->CNOS_DESCRIPCION = 'FONTANEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7222';
    $cno->CNOS_DESCRIPCION = 'MONTADORES-INSTALADORES DE GAS EN EDIFICIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7223';
    $cno->CNOS_DESCRIPCION = 'INSTALADORES DE CONDUCTOS EN OBRA PÚBLICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7231';
    $cno->CNOS_DESCRIPCION = 'PINTORES Y EMPAPELADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7232';
    $cno->CNOS_DESCRIPCION = 'PINTORES EN LAS INDUSTRIAS MANUFACTURERAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7240';
    $cno->CNOS_DESCRIPCION = 'SOLADORES, COLOCADORES DE PARQUET Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7250';
    $cno->CNOS_DESCRIPCION = 'MECÁNICOS-INSTALADORES DE REFRIGERACIÓN Y CLIMATIZACIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7291';
    $cno->CNOS_DESCRIPCION = 'MONTADORES DE CUBIERTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7292';
    $cno->CNOS_DESCRIPCION = 'INSTALADORES DE MATERIAL AISLANTE TÉRMICO Y DE INSONORIZACIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7293';
    $cno->CNOS_DESCRIPCION = 'CRISTALEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7294';
    $cno->CNOS_DESCRIPCION = 'MONTADORES-INSTALADORES DE PLACAS DE ENERGÍA SOLAR';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7295';
    $cno->CNOS_DESCRIPCION = 'PERSONAL DE LIMPIEZA DE FACHADAS DE EDIFICIOS Y CHIMENEAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7311';
    $cno->CNOS_DESCRIPCION = 'MOLDEADORES Y MACHEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7312';
    $cno->CNOS_DESCRIPCION = 'SOLDADORES Y OXICORTADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7313';
    $cno->CNOS_DESCRIPCION = 'CHAPISTAS Y CALDEREROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7314';
    $cno->CNOS_DESCRIPCION = 'MONTADORES DE ESTRUCTURAS METÁLICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7315';
    $cno->CNOS_DESCRIPCION = 'MONTADORES DE ESTRUCTURAS CABLEADAS Y EMPALMADORES DE CABLES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7321';
    $cno->CNOS_DESCRIPCION = 'HERREROS Y FORJADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7322';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE LA FABRICACIÓN DE HERRAMIENTAS, MECÁNICO-AJUSTADORES, MODELISTAS, MATRICEROS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7323';
    $cno->CNOS_DESCRIPCION = 'AJUSTADORES Y OPERADORES DE MÁQUINAS-HERRAMIENTA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7324';
    $cno->CNOS_DESCRIPCION = 'PULIDORES DE METALES Y AFILADORES DE HERRAMIENTAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7401';
    $cno->CNOS_DESCRIPCION = 'MECÁNICOS Y AJUSTADORES DE VEHÍCULOS DE MOTOR';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7402';
    $cno->CNOS_DESCRIPCION = 'MECÁNICOS Y AJUSTADORES DE MOTORES DE AVIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7403';
    $cno->CNOS_DESCRIPCION = 'MECÁNICOS Y AJUSTADORES DE MAQUINARIA AGRÍCOLA E INDUSTRIAL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7404';
    $cno->CNOS_DESCRIPCION = 'MECÁNICOS Y AJUSTADORES DE MAQUINARIA NAVAL Y FERROVIARIA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7405';
    $cno->CNOS_DESCRIPCION = 'REPARADORES DE BICICLETAS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7510';
    $cno->CNOS_DESCRIPCION = 'ELECTRICISTAS DE LA CONSTRUCCIÓN Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7521';
    $cno->CNOS_DESCRIPCION = 'MECÁNICOS Y REPARADORES DE EQUIPOS ELÉCTRICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7522';
    $cno->CNOS_DESCRIPCION = 'INSTALADORES Y REPARADORES DE LÍNEAS ELÉCTRICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7531';
    $cno->CNOS_DESCRIPCION = 'MECÁNICOS Y REPARADORES DE EQUIPOS ELECTRÓNICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7532';
    $cno->CNOS_DESCRIPCION = 'INSTALADORES Y REPARADORES EN ELECTROMEDICINA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7533';
    $cno->CNOS_DESCRIPCION = 'INSTALADORES Y REPARADORES EN TECNOLOGÍAS DE LA INFORMACIÓN Y LAS COMUNICACIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7611';
    $cno->CNOS_DESCRIPCION = 'RELOJEROS Y MECÁNICOS DE INSTRUMENTOS DE PRECISIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7612';
    $cno->CNOS_DESCRIPCION = 'LUTIERES Y SIMILARES; AFINADORES DE INSTRUMENTOS MUSICALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7613';
    $cno->CNOS_DESCRIPCION = 'JOYEROS, ORFEBRES Y PLATEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7614';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE LA CERÁMICA, ALFAREROS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7615';
    $cno->CNOS_DESCRIPCION = 'SOPLADORES, MODELADORES, LAMINADORES, CORTADORES Y PULIDORES DE VIDRIO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7616';
    $cno->CNOS_DESCRIPCION = 'ROTULISTAS, GRABADORES DE VIDRIO, PINTORES DECORATIVOS DE ARTÍCULOS DIVERSOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7617';
    $cno->CNOS_DESCRIPCION = 'ARTESANOS EN MADERA Y MATERIALES SIMILARES; CESTEROS, BRUCEROS Y TRABAJADORES AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7618';
    $cno->CNOS_DESCRIPCION = 'ARTESANOS EN TEJIDOS, CUEROS Y MATERIALES SIMILARES, PREPARADORES DE FIBRA Y TEJEDORES CON TELARES ARTESANOS O DE TEJIDOS DE PUNTO Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7619';
    $cno->CNOS_DESCRIPCION = 'ARTESANOS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7621';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE PROCESOS DE PREIMPRESIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7622';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE PROCESOS DE IMPRESIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7623';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE PROCESOS DE ENCUADERNACIÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7701';
    $cno->CNOS_DESCRIPCION = 'MATARIFES Y TRABAJADORES DE LAS INDUSTRIAS CÁRNICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7702';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE LAS INDUSTRIAS DEL PESCADO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7703';
    $cno->CNOS_DESCRIPCION = 'PANADEROS, PASTELEROS Y CONFITEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7704';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DEL TRATAMIENTO DE LA LECHE Y ELABORACIÓN DE PRODUCTOS LÁCTEOS (INCLUIDOS HELADOS)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7705';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES CONSERVEROS DE FRUTAS Y HORTALIZAS Y TRABAJADORES DE LA ELABORACIÓN DE BEBIDAS NO ALCOHÓLICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7706';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE LA ELABORACIÓN DE BEBIDAS ALCOHÓLICAS DISTINTAS DEL VINO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7707';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DE LA ELABORACIÓN DEL VINO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7708';
    $cno->CNOS_DESCRIPCION = 'PREPARADORES Y ELABORADORES DEL TABACO Y SUS PRODUCTOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7709';
    $cno->CNOS_DESCRIPCION = 'CATADORES Y CLASIFICADORES DE ALIMENTOS Y BEBIDAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7811';
    $cno->CNOS_DESCRIPCION = 'TRABAJADORES DEL TRATAMIENTO DE LA MADERA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7812';
    $cno->CNOS_DESCRIPCION = 'AJUSTADORES Y OPERADORES DE MÁQUINAS PARA TRABAJAR LA MADERA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7820';
    $cno->CNOS_DESCRIPCION = 'EBANISTAS Y TRABAJADORES AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7831';
    $cno->CNOS_DESCRIPCION = 'SASTRES, MODISTOS, PELETEROS Y SOMBREREROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7832';
    $cno->CNOS_DESCRIPCION = 'PATRONISTAS PARA PRODUCTOS EN TEXTIL Y PIEL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7833';
    $cno->CNOS_DESCRIPCION = 'CORTADORES DE TEJIDOS, CUERO, PIEL Y OTROS MATERIALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7834';
    $cno->CNOS_DESCRIPCION = 'COSTUREROS A MANO, BORDADORES Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7835';
    $cno->CNOS_DESCRIPCION = 'TAPICEROS, COLCHONEROS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7836';
    $cno->CNOS_DESCRIPCION = 'CURTIDORES Y PREPARADORES DE PIELES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7837';
    $cno->CNOS_DESCRIPCION = 'ZAPATEROS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7891';
    $cno->CNOS_DESCRIPCION = 'BUCEADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7892';
    $cno->CNOS_DESCRIPCION = 'PEGADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7893';
    $cno->CNOS_DESCRIPCION = 'CLASIFICADORES Y PROBADORES DE PRODUCTOS (EXCEPTO ALIMENTOS, BEBIDAS Y TABACO)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7894';
    $cno->CNOS_DESCRIPCION = 'FUMIGADORES Y OTROS CONTROLADORES DE PLAGAS Y MALAS HIERBAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '7899';
    $cno->CNOS_DESCRIPCION = 'OFICIALES, OPERARIOS Y ARTESANOS DE OTROS OFICIOS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8111';
    $cno->CNOS_DESCRIPCION = 'MINEROS Y OTROS OPERADORES EN INSTALACIONES MINERAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8112';
    $cno->CNOS_DESCRIPCION = 'OPERADORES EN INSTALACIONES PARA LA PREPARACIÓN DE MINERALES Y ROCAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8113';
    $cno->CNOS_DESCRIPCION = 'SONDISTAS Y TRABAJADORES AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8114';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MAQUINARIA PARA FABRICAR PRODUCTOS DERIVADOS DE MINERALES NO METÁLICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8121';
    $cno->CNOS_DESCRIPCION = 'OPERADORES EN INSTALACIONES PARA LA OBTENCIÓN Y TRANSFORMACIÓN DE METALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8122';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PULIDORAS, GALVANIZADORAS Y RECUBRIDORAS DE METALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8131';
    $cno->CNOS_DESCRIPCION = 'OPERADORES EN PLANTAS INDUSTRIALES QUÍMICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8132';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA FABRICAR PRODUCTOS FARMACÉUTICOS, COSMÉTICOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8133';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE LABORATORIOS FOTOGRÁFICOS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8141';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA FABRICAR PRODUCTOS DE CAUCHO Y DERIVADOS DE RESINAS NATURALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8142';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA FABRICAR PRODUCTOS DE MATERIAL PLÁSTICO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8143';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA FABRICAR PRODUCTOS DE PAPEL Y CARTÓN';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8144';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE SERRERÍAS, DE MÁQUINAS DE FABRICACIÓN DE TABLEROS Y DE INSTALACIONES AFINES PARA EL TRATAMIENTO DE LA MADERA Y EL CORCHO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8145';
    $cno->CNOS_DESCRIPCION = 'OPERADORES EN INSTALACIONES PARA LA PREPARACIÓN DE PASTA DE PAPEL Y FABRICACIÓN DE PAPEL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8151';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA PREPARAR FIBRAS, HILAR Y DEVANAR';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8152';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE TELARES Y OTRAS MÁQUINAS TEJEDORAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8153';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS DE COSER Y BORDAR';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8154';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS DE BLANQUEAR, TEÑIR, ESTAMPAR Y ACABAR TEXTILES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8155';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA TRATAR PIELES Y CUERO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8156';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA LA FABRICACIÓN DEL CALZADO, MARROQUINERÍA Y GUANTERÍA DE PIEL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8159';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA FABRICAR PRODUCTOS TEXTILES NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8160';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS PARA ELABORAR PRODUCTOS ALIMENTICIOS, BEBIDAS Y TABACO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8170';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS DE LAVANDERÍA Y TINTORERÍA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8191';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE HORNOS E INSTALACIONES DE VIDRIERÍA Y CERÁMICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8192';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE CALDERAS Y MÁQUINAS DE VAPOR';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8193';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MÁQUINAS DE EMBALAJE, EMBOTELLAMIENTO Y ETIQUETADO';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8199';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE INSTALACIONES Y MAQUINARIA FIJAS NO CLASIFICADOS BAJO OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8201';
    $cno->CNOS_DESCRIPCION = 'ENSAMBLADORES DE MAQUINARIA MECÁNICA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8202';
    $cno->CNOS_DESCRIPCION = 'ENSAMBLADORES DE EQUIPOS ELÉCTRICOS Y ELECTRÓNICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8209';
    $cno->CNOS_DESCRIPCION = 'MONTADORES Y ENSAMBLADORES NO CLASIFICADOS EN OTROS EPÍGRAFES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8311';
    $cno->CNOS_DESCRIPCION = 'MAQUINISTAS DE LOCOMOTORAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8312';
    $cno->CNOS_DESCRIPCION = 'AGENTES DE MANIOBRAS FERROVIARIAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8321';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MAQUINARIA AGRÍCOLA MÓVIL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8322';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MAQUINARIA FORESTAL MÓVIL';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8331';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE MAQUINARIA DE MOVIMIENTOS DE TIERRAS Y EQUIPOS SIMILARES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8332';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE GRÚAS, MONTACARGAS Y DE MAQUINARIA SIMILAR DE MOVIMIENTO DE MATERIALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8333';
    $cno->CNOS_DESCRIPCION = 'OPERADORES DE CARRETILLAS ELEVADORAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8340';
    $cno->CNOS_DESCRIPCION = 'MARINEROS DE PUENTE, MARINEROS DE MÁQUINAS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8411';
    $cno->CNOS_DESCRIPCION = 'CONDUCTORES PROPIETARIOS DE AUTOMÓVILES, TAXIS Y FURGONETAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8412';
    $cno->CNOS_DESCRIPCION = 'CONDUCTORES ASALARIADOS DE AUTOMÓVILES, TAXIS Y FURGONETAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8420';
    $cno->CNOS_DESCRIPCION = 'CONDUCTORES DE AUTOBUSES Y TRANVÍAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8431';
    $cno->CNOS_DESCRIPCION = 'CONDUCTORES PROPIETARIOS DE CAMIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8432';
    $cno->CNOS_DESCRIPCION = 'CONDUCTORES ASALARIADOS DE CAMIONES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '8440';
    $cno->CNOS_DESCRIPCION = 'CONDUCTORES DE MOTOCICLETAS Y CICLOMOTORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9100';
    $cno->CNOS_DESCRIPCION = 'EMPLEADOS DOMÉSTICOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9210';
    $cno->CNOS_DESCRIPCION = 'PERSONAL DE LIMPIEZA DE OFICINAS, HOTELES Y OTROS ESTABLECIMIENTOS SIMILARES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9221';
    $cno->CNOS_DESCRIPCION = 'LIMPIADORES EN SECO A MANO Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9222';
    $cno->CNOS_DESCRIPCION = 'LIMPIADORES DE VEHÍCULOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9223';
    $cno->CNOS_DESCRIPCION = 'LIMPIADORES DE VENTANAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9229';
    $cno->CNOS_DESCRIPCION = 'OTRO PERSONAL DE LIMPIEZA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9310';
    $cno->CNOS_DESCRIPCION = 'AYUDANTES DE COCINA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9320';
    $cno->CNOS_DESCRIPCION = 'PREPARADORES DE COMIDAS RÁPIDAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9410';
    $cno->CNOS_DESCRIPCION = 'VENDEDORES CALLEJEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9420';
    $cno->CNOS_DESCRIPCION = 'REPARTIDORES DE PUBLICIDAD, LIMPIABOTAS Y OTROS TRABAJADORES DE OFICIOS CALLEJEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9431';
    $cno->CNOS_DESCRIPCION = 'ORDENANZAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9432';
    $cno->CNOS_DESCRIPCION = 'MOZOS DE EQUIPAJE Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9433';
    $cno->CNOS_DESCRIPCION = 'REPARTIDORES, RECADISTAS Y MENSAJEROS A PIE';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9434';
    $cno->CNOS_DESCRIPCION = 'LECTORES DE CONTADORES Y RECAUDADORES DE MÁQUINAS RECREATIVAS Y EXPENDEDORAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9441';
    $cno->CNOS_DESCRIPCION = 'RECOGEDORES DE RESIDUOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9442';
    $cno->CNOS_DESCRIPCION = 'CLASIFICADORES DE DESECHOS, OPERARIOS DE PUNTO LIMPIO Y RECOGEDORES DE CHATARRA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9443';
    $cno->CNOS_DESCRIPCION = 'BARRENDEROS Y AFINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9490';
    $cno->CNOS_DESCRIPCION = 'OTRAS OCUPACIONES ELEMENTALES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9511';
    $cno->CNOS_DESCRIPCION = 'PEONES AGRÍCOLAS (EXCEPTO EN HUERTAS, INVERNADEROS, VIVEROS Y JARDINES)';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9512';
    $cno->CNOS_DESCRIPCION = 'PEONES AGRÍCOLAS EN HUERTAS, INVERNADEROS, VIVEROS Y JARDINES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9520';
    $cno->CNOS_DESCRIPCION = 'PEONES GANADEROS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9530';
    $cno->CNOS_DESCRIPCION = 'PEONES AGROPECUARIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9541';
    $cno->CNOS_DESCRIPCION = 'PEONES DE LA PESCA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9542';
    $cno->CNOS_DESCRIPCION = 'PEONES DE LA ACUICULTURA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9543';
    $cno->CNOS_DESCRIPCION = 'PEONES FORESTALES Y DE LA CAZA';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9601';
    $cno->CNOS_DESCRIPCION = 'PEONES DE OBRAS PÚBLICAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9602';
    $cno->CNOS_DESCRIPCION = 'PEONES DE LA CONSTRUCCIÓN DE EDIFICIOS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9603';
    $cno->CNOS_DESCRIPCION = 'PEONES DE LA MINERÍA, CANTERAS Y OTRAS INDUSTRIAS EXTRACTIVAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9700';
    $cno->CNOS_DESCRIPCION = 'PEONES DE LAS INDUSTRIAS MANUFACTURERAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9811';
    $cno->CNOS_DESCRIPCION = 'PEONES DEL TRANSPORTE DE MERCANCÍAS Y DESCARGADORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9812';
    $cno->CNOS_DESCRIPCION = 'CONDUCTORES DE VEHÍCULOS DE TRACCIÓN ANIMAL PARA EL TRANSPORTE DE PERSONAS Y SIMILARES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '9820';
    $cno->CNOS_DESCRIPCION = 'REPONEDORES';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '0011';
    $cno->CNOS_DESCRIPCION = 'OFICIALES DE LAS FUERZAS ARMADAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '0012';
    $cno->CNOS_DESCRIPCION = 'SUBOFICIALES DE LAS FUERZAS ARMADAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();
    $cno = new Cno;
    $cno->CNOS_CODIGO = '0020';
    $cno->CNOS_DESCRIPCION = 'TROPA Y MARINERÍA DE LAS FUERZAS ARMADAS';
    $cno->CNOS_CREADOPOR = 'admin';
    $cno->save();


            

    	}

    }
